#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' 
bold=$(tput bold)
normal=$(tput sgr0)
g++ -DLOCAL  cppcode.cpp -std=c++20

if [ $? -ne 0 ]
then
    echo -e "${RED}${bold}\033[1mCompilation Failed\033[0m${NC}${normal}" 
    exit 1
fi 
for (( i=1 ; i<=$1 ; i++ )); 
do
    echo ""
    ./a.out < "in$((i)).txt"
done